language: python
python:
- '3.6'
sudo: required
cache:
- docker
services:
- docker
install:
- sudo pip install --upgrade pip
- sudo pip install coveralls
script:
- export CURRENT_PATH=`pwd`
- docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter-ws /bin/bash -c "cd  $CURRENT_PATH && coverage run -m unittest discover hepdata_converter_ws/testsuite 'test_*'"
- docker run -v $CURRENT_PATH:$CURRENT_PATH hepdata/hepdata-converter-ws /bin/bash -c "cd  $CURRENT_PATH && python setup.py install && hepdata-converter-ws -v"

after_success:
- coveralls

deploy:
  provider: pypi
  user: hepdata
  password:
    secure: X5bMcItjHE9FL2CHZ1HEKA9XUzeSun9Oo2YQTKX5QI+YSeJvDZh+ph/2WAfW5W09cnuscSbwkUgZpXDedhygqVwbSNxJzSLWpOw5bnvWypB/ml1ZZ0n0w89up2DYKJQLTC26aHQHqVhHD51oefA9lAYWNjhkanPT+uincNbXmfUpP/DeNtIk4omdkFi64QjNlN7WUC85jGPEit4C+tMuWEcrAfI23spOJGrN6AXURMBJ4V1EToE+AdRB6v6kT6JaN08EoWIOgrVisiM8tcHgHLyDTox61LiGRxmEspYWhK21fgZfOCsklYAacWDaBjzQXbcqh9EDjOl4jSjxVTHv8ZIZ0TfITZD87jbhaESKE7V5TgyrXBX5gGLzfL7ThCQXWdGn0dUvBuBorBwleR9R1l5eBFfTQn895n4x0ZXXBK/GZXDwj3yi0BVumDX4SKKlGX0NbaAcqnthJr/ZUBWbAXV/SfNNsJezT4z96jRHfJ0hDbaYTl1bzc0Ih1iZWSVWVQgFNdGdP4ELTUxiUNjSA6meyWdUloFj5yR7NYWbXtCBfNeBJjMeKkKVI41Jt8mx4u4ayXTZhs9Mxmwng/GpBs/edKvFMjKrNbTBf15v635cYVJcGeUwMDSYbR7jVOARWwWsX6DiYiMvz4F95uPoxnpFAarzptp1f4qvkXeyp9c=
  on:
    tags: true
    repo: HEPData/hepdata-converter-ws
    branch: master
